---
- hosts: dc00
  gather_facts: no
  tasks:

    - name: Execute a command in the remote shell, stdout goes to the specified file on the remote
      win_shell: C:\CSV\Add-NewUsers.ps1  >> C:\log.txt
